image: prusa/oe

stages:
  - build
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: "recursive"
  GIT_DEPTH: "120"

before_script:
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - echo "$DEV_DEPLOY_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - ssh-keyscan github.com >> ~/.ssh/known_hosts
  - cat ~/.ssh/known_hosts
  - mkdir -p build/conf && touch build/conf/auto.conf
  - cat build/conf/auto.conf
  - echo "$DEV_CERT" > sources/meta-prusa/files/ca.cert.pem
  - echo "$DEV_KEY" > sources/meta-prusa/files/ca.key.pem
  - export VERSION=$(./version.sh)
  - echo "Version ${VERSION}"
  - export BB_ENV_EXTRAWHITE="${BB_ENV_EXTRAWHITE} CI_COMMIT_REF_NAME CI_COMMIT_TAG"

cache:
  key: build-cache-honister
  paths:
    - build/cache

b:raucb-development:
  stage: build

  only: 
    - tags
    - merge_requests
    - web

  script:
    - cat build/conf/auto.conf
    - source oe-init-build-env
    - bitbake --quiet sla-update-bundle
    - cd ..
    - mv build/tmp/deploy/images/prusa64-sl1/sla-update-bundle-prusa64-sl1-*.raucb ${VERSION}.dev-key.raucb
    - mv build/tmp/deploy/images/prusa64-sl1/sla-initramfs-prusa64-sl1-*.manifest ${VERSION}.initramfs.manifest
    - mv build/tmp/deploy/images/prusa64-sl1/sla-image-prusa64-sl1-*.manifest ${VERSION}.manifest
    - mv build/tmp/deploy/images/prusa64-sl1/Image-initramfs--*.bin .
    - mv Image-initramfs--* `ls Image-initramfs--* | sed 's#^Image-initramfs--v\([^-]\+\)-.*$#Image-\1#'`
    - mv changelog.md ${VERSION}.changelog.md
    - cat build/tmp/log/cooker/prusa64-sl1/console-latest.log | xz > log.txt.xz

  artifacts:
    expire_in: 1 week
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - ./*.raucb
      - ./*.manifest
      - ./*.changelog.md
      - ./log.txt.xz
      - ./Image-*

b:raucb-production:
  stage: build
  when: manual

  dependencies: []

  only:
    refs:
      - tags
      - merge_requests
      - web

    variables:
      - $RAUC_CERT_FILE
      - $RAUC_KEY_FILE
      - $RAUC_PKCS11_PIN
      - $PKCS11_PROXY_SOCKET
      - $RAUC_PKCS11_MODULE
      - $CERT_VALID_DAYS

  script:
    - ./sign_cert_check.sh
    - source oe-init-build-env
    - export BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE RAUC_CERT_FILE RAUC_KEY_FILE RAUC_PKCS11_PIN PKCS11_PROXY_SOCKET RAUC_PKCS11_MODULE"
    - bitbake sla-update-bundle
    - cd ..
    - mv build/tmp/deploy/images/prusa64-sl1/sla-update-bundle-prusa64-sl1-*.raucb ${VERSION}.prod-key.raucb
    - mv build/tmp/deploy/images/prusa64-sl1/sla-initramfs-prusa64-sl1-*.manifest ${VERSION}.initramfs.manifest
    - mv build/tmp/deploy/images/prusa64-sl1/sla-image-prusa64-sl1-*.manifest ${VERSION}.manifest
    - mv changelog.md ${VERSION}.changelog.md

  artifacts:
    expire_in: 1 week
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - ./*.raucb
      - ./*.manifest
      - ./*.changelog.md

b:tools:
  stage: build
  when: manual

  dependencies: []

  only:
    - tags
    - merge_requests
    - web

  script:
    - source oe-init-build-env
    - bitbake --quiet sla-dev-image sla-bootstrap
    - xz -T0 --verbose tmp/deploy/images/prusa64-sl1/*.rootfs.wic
    - cd ..
    - mv build/tmp/deploy/images/prusa64-sl1/sla-dev-image-prusa64-sl1-*.wic.xz ${VERSION}.devsd.xz
    - mv build/tmp/deploy/images/prusa64-sl1/sla-dev-image-prusa64-sl1-*.wic.bmap ${VERSION}.devsd.bmap
    - mv build/tmp/deploy/images/prusa64-sl1/sla-dev-image-prusa64-sl1-*.manifest ${VERSION}.devsd.manifest
    - mv build/tmp/deploy/images/prusa64-sl1/sla-bootstrap-prusa64-sl1-*.rootfs.wic.xz ${VERSION}.bootstrapsd.xz
    - mv build/tmp/deploy/images/prusa64-sl1/sla-bootstrap-prusa64-sl1-*.rootfs.wic.bmap ${VERSION}.bootstrapsd.bmap
    - cat build/tmp/log/cooker/prusa64-sl1/console-latest.log | xz > log.txt.xz

  artifacts:
    expire_in: 1 week
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - ./*.devsd.*
      - ./*.bootstrapsd.*
      - ./log.txt.xz

d:raucb-development:
  stage: deploy
  when: manual
  cache: {}
  
  dependencies:
    - b:raucb-development

  only:
    - tags
    - merge_requests
    - web

  script:
    - >
        lftp -c "
        set sftp:ssl-force yes;
        open -u ${DEPLOY_FTP_USER},${DEPLOY_FTP_PASS} ${DEPLOY_FTP_HOST};
        put -O ${DEST} ${VERSION}.dev-key.raucb;
        put -O ${DEST} ${VERSION}.changelog.md;
        "
    - echo "put ${VERSION}.raucb" | sftp ${DEV_DEPLOY_USER}@${DEV_DEPLOY_HOST}
    - echo "put ${VERSION}.changelog.md" | sftp ${DEV_DEPLOY_USER}@${DEV_DEPLOY_HOST}

d:raucb-production:
  stage: deploy
  when: manual
  cache: {}

  dependencies:
    - b:raucb-production

  only:
    - tags
    - merge_requests
    - web

  script:
    - >
        lftp -c "
        set sftp:ssl-force yes;
        open -u ${DEPLOY_FTP_USER},${DEPLOY_FTP_PASS} ${DEPLOY_FTP_HOST};
        put -O ${DEST} ${VERSION}.prod-key.raucb;
        put -O ${DEST} ${VERSION}.changelog.md;
        "
    - echo "put ${VERSION}.prod-key.raucb" | sftp ${DEV_DEPLOY_USER}@${DEV_DEPLOY_HOST}
    - echo "put ${VERSION}.changelog.md" | sftp ${DEV_DEPLOY_USER}@${DEV_DEPLOY_HOST}

d:tools:
  stage: deploy
  when: manual
  cache: {}

  dependencies:
    - b:tools

  only:
    - tags
    - merge_requests
    - web

  script:
    - echo "put ${VERSION}.devsd.xz" | sftp ${DEV_DEPLOY_USER}@${DEV_DEPLOY_HOST}
    - echo "put ${VERSION}.devsd.bmap" | sftp ${DEV_DEPLOY_USER}@${DEV_DEPLOY_HOST}
    - echo "put ${VERSION}.bootstrapsd.xz" | sftp ${DEV_DEPLOY_USER}@${DEV_DEPLOY_HOST}
    - echo "put ${VERSION}.bootstrapsd.bmap" | sftp ${DEV_DEPLOY_USER}@${DEV_DEPLOY_HOST}
